<section>
	<h1>List</h1>
	<?php 
	   	echo '<table class="table table-hover">';
		echo "<tr>
			<th>UserName</th>
			<th>E-mail</th>
			<th>Sex</th>
			<th>Website</th>
			<th>Delete member</th></tr>";
	
	   	foreach($listMembers As $member) {
					
			echo "<tr><td>";
			echo $member['username'];
			echo "</td><td>";
			echo '<a href="mailto:' . $member['email'] . '">' . $member['email'] . '</a>';
			echo "</td><td>";
			if ($member['sex'])
				echo 'Male';
			else
				echo 'Female';
			echo "</td><td>";
			echo '<a href="' . $member['website'] . '">' . $member['website'] . '</a>';
			echo "</td><td>";
			echo '<a href="/members/delete?username=' . $member['username'] . '">Delete</a>';
			echo "</td>\n";
		}
		echo "</table>";
		?>

</section>
