<section>
<h1>sign up</h1>
	<p>	<?php echo $message; ?> </p>
   	 <form method="post" action="" class="form-horizontal well span6">
		
			<div class="control-group">
			    <label class="control-label" for="username">Nickname:</label>
				<div class="controls">
					<input type="text" name="username" id="username" placeholder="Ex : Toto" size="45" maxlength="30" autofocus />
				</div>
			</div>
			
			<div class="control-group">
		    	<label class="control-label" for="email">Mail:</label>
				<div class="controls">
					<input type="text" name="email" id="email" placeholder="Ex : organizer@gmail.com" size="45" maxlength="30" />
				</div>
			</div>
		    
			<div class="control-group">
				<label class="control-label" for="password">Password:</label>
				<div class="controls">
					<input type="password" name="password" id="password" placeholder="Ex : bAZKbfernbJFbe" size="45" maxlength="30" />
				</div>
			</div>
		
			<div class="control-group">
			    <label class="control-label" for="sex">Sexe:</label>
				<div class="controls">				
					<select name="sex" id="sex">
				   		<option value="1">Homme</option>
				   		<option value="0">Femme</option>
					</select>
				</div>
			</div>
			<div class="controls">
			<button type="submit" class="btn btn-primary" onsubmit="return validateSignUpForm();">Sign up</button>
			<button class="btn" onclick="return resetSignupForm();">Clear</button>
			</div>
	</form>
</section>

