<section>
	<h1>Edit my profile</h1>
	<form method="post" action="/profile/edit" class="form-horizontal well span6">
		<div class="control-group">
			<label class="control-label" for="username">Nickname:</label>
			<div class="controls">
				<input type="text" name="username" id="username" value="<?php echo $username; ?>" size="45" maxlength="30" autofocus required />
			</div>
		</div>
			
		<div class="control-group">
	    	<label class="control-label" for="description">Description:</label>
			<div class="controls">
				<textarea name="description" id="description" rows="5" cols="50"><?php echo $desc; ?></textarea>
			</div>
		</div>
	
		<div class="control-group">
			<label class="control-label" for="website">Website:</label>
			<div class="controls">
				<input type="text" name="website" id="website" value="<?php echo $website; ?>" size="45" maxlength="30"/>
			</div>
		</div>
		
		<div class="controls">
			<button type="submit" class="btn btn-primary">Send</button>
			<button onclick="this.form.reset();" class="btn">Clear</button>
		</div>

	</form>
</section>
