<section>
<?php
	if(isset($_GET['id']) && $_GET['id'] != null && $_GET['id'] > 0 && $_GET['id'] < Members::getLastId())
	{
	?>

<h1>Profile of <?php echo $profile->getMember()->getUserName(); ?></h1>

<?php
	if($profile != null && $profile->getUpdates() != null) {
		foreach($profile->getUpdates() as $update) {
			echo '<p>';
			echo $update->getDate() . '<br />';
			echo $update->getContent() . '<br />';
			echo $update->getService() . '<br />';
			echo '</p>';
		}
	}
?>

<?php
	}
	else
	{
	?>

<p> No member found </p>
<?php
	}
	?>

</section>
