<?php
	if(isset($profile) && $profile != null && $profile['member'] != null)
	{
	?>
<section>
<h1>Profile of <?php echo $profile['member']['username']; ?></h1>
<img src='<?php echo $profile['member']['image']; ?>' />

<?php
	// If the connected member is watching his own wall
	if(isset($_SESSION['connected']) && $_SESSION['connected'] == true) {
		if($_SESSION['idMember'] == $profile['member']['idMember']) {
			// Display a form to post a new status and/or image
			?>
			<form method='post' action='/profile/add' enctype='multipart/form-data'>
				<label for='content'>Status : </label>
				<textarea name='content' id='content' rows='3' cols='30'></textarea><br/>
				<label for='image'>Image : </label>
				<input type='file' name='image' id='image' />
				<input type='submit' value='Submit' />
			</form>
			<?php
		}
		else {
			echo '<button type="button" onclick="updateWall()">Update Wall</button>';
			echo '<div id="update"></div>';
		}
	}
	// If the member ever posted something
	if($profile != null && $profile['updates'] != null) {
		echo '<div id="lastUpdate" style="display:none">' . $profile['updates'][0]['date'] . '</div>';
		echo '<div id="idMember" style="display:none">' . $profile['member']['idMember'] . '</div>'; 
		// Display all updates
		foreach($profile['updates'] as $update) {
			echo '<p>';
			echo $update['date'] . '<br />';
			echo $update['content'] . '<br />';
			echo $update['service'] . '<br />';
			// If the member connected is the author of the status, display a link to delete his status
			if($update['idMember'] == $_SESSION['idMember']) {
				echo '<a href="/profile/delete?idUpdate='.$update['idUpdate'].'">Delete</a>';
			}
			// If a status has comments, display them too
			if($update['comment'] != null) {
				foreach($update['comment'] as $comment) {
					echo '<div id="comment">' .
						 $comment['date'] . '<br />' .
						 $comment['content'] . '<br />';
					// If the member connected is the author of the comment, display a link to delete his comment
					if($comment['idAuthor'] == $_SESSION['idMember']) {
						echo '<a href="/profile/deleteComment?idComment='.$comment['idComment'].'">Delete comment</a>';
					}
					echo '</div>';
				}
			}
			// Comment form
			echo '<form method="post" action="/profile/comment?idMember=' . $update['idMember'] . '&idUpdate=' . $update['idUpdate'] . '">' .
				 '<textarea name="comment" id="comment" rows="1" cols="30"></textarea>' .
				 '<input type="submit" value="Comment" />' .
				 '</form>';
			echo '</p>';
		}
	}
}
else {
	echo 'No member found';
}
	?>
</section>
