<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<title>Title of the page</title>

	<link href="../../bootstrap/css/bootstrap.css" rel="stylesheet">
</head>
<body>
	<div id="header">
		<a href='/'><img src="img/logo.png" alt="logo" /></a>
	
		<h2> Dare and get known ! </h2>
		<?php 
		// If the user is logged, display personnal informations
		if (isset($_SESSION['connected']) && $_SESSION['connected'] == true)
		{
		?>
		<p>
			<?php echo $_SESSION['pseudo']; ?>
			<br />
			<a href="/profile/edit">Edit my profile</a>
			<a href="/members/logout">Log out</a>
		</p>
		<?php
		}
		// If the user is not logged, display log in form and a link to the sign up page
		else
		{
		?>
			<div id="LogBanner">
			<form method="post" action="/members/signin">
				<label for="pseudo">Username :</label>
				<input type="text" name="pseudo" id="pseudo" /> 
				<label for="password">Password :</label>
				<input type="password" name="password" id="password" />
				<input type="submit" value="Login" />
			</form>
			<a href="/members/signup">Create Account</a>
			</div>
		<?php
		}
		?>
</div>
