<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<title>DareU</title>

	<link href="../../bootstrap/css/bootstrap.css" rel="stylesheet">
</head>
<body>
	<header>
		<div class="navbar navbar-static-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<a class ="brand" href='/'>DareU</a>
					<ul class="nav pull-right">
					<li class="divider-vertical"></li>
					<?php 
					// If the user is logged, display personnal informations
					if (isset($_SESSION['connected']) && $_SESSION['connected'] == true)
					{
						if($_SESSION['isAdmin'])
						{
					?>
							<li><a href="/members/list">Members administration</a></li>
							<li class="divider-vertical"></li>
						<?php
						}
						?>
			
						<li><a href="/profile"><?php echo $_SESSION['pseudo']; ?></a></li>
						<li><a href="/profile/edit">Edit my profile</a></li>
						<li><a href="/members/logout">Log out</a></li>
					<?php
					}
					// If the user is not logged, display log in form and a link to the sign up page
					else
					{
					?>
					<li><form class="form-inline navbar-form pull-left" method="post" action="/members/signin">
							<label for="pseudo">Username :</label>
							<input type="text" name="pseudo" id="pseudo" class="span2" /> 
							<label for="password">Password :</label>
							<input type="password" name="password" id="password" class="span2" />
							<button type="submit" class="btn">Log In</button>
						</form>
					</li>
						<li><a href="/members/signup">Create Account</a></li>
					<?php
					}
					?>
					</ul>
				</div>
			</div>
		</div>
</header>
<div class="container">
