<section>
<h1>Title</h1>
<div id="page">
				<article>

			<?php
			 		echo "<table><tr>";
			 		foreach($frontProfiles As $member) {
						echo "<td>";
						?>
						<a href="/profile/view?id=<?php echo $member['idMember']; ?>">
				   		<?php echo $member['username']; ?>
						</a>
				   		<br />
				   		<img 	src="<?php echo $member['image']; ?>"
				   				alt="Profile image"
								class="img-polaroid"
				  	 	/>
						</a>
				   		<br />
				  
				  	<?php
					}
			 		echo "</tr></table>";
					?>
				
				</article>
		</div>
	</section>
