<section>
<h1>Title</h1>
<div id="page">
				<article>

			<?php
			 		echo "<table><tr>";
			 		foreach($frontProfiles As $member) {
						echo "<td>";
				   		echo $member['pseudo'] . '<br />';
				   		?>

				   		<img 	src="<?php echo $member['image']; ?>"
				   				alt="Profile image"
								class="img-polaroid"
				  	 	/>
				   		<br />
				  
				  	<?php
					}
			 		echo "</tr></table>";
					?>
				
				</article>
		</div>
	</section>
